version: '2'
services:
    web:
        image: nginx
        container_name: vooxer
        volumes:
            - ./deploy:/usr/share/nginx/html
        expose:
            - 80
        networks:
            - vooxer
            - nginx-proxy
        environment:
            NGINX_HOST: vooxer.thomazot.com.br
            NGINX_PORT: 80
            VIRTUAL_HOST: vooxer.thomazot.com.br
            LETSENCRYPT_HOST: vooxer.thomazot.com.br
            LETSENCRYPT_EMAIL: contato@thomazot.com.br
networks:
    vooxer:
    nginx-proxy:
        external:
            name: nginx-net
