version: '2'
services:
    web:
        image: nginx
        container_name: vooxer
        volumes:
            - ./deploy:/usr/share/nginx/html
        expose:
            - 80
        networks:
            - vooxer
            - nginx-proxy
        environment:
            NGINX_HOST: vooxer.localhost
            NGINX_PORT: 80
            VIRTUAL_HOST: vooxer.localhost
networks:
    vooxer:
    nginx-proxy:
        external:
            name: proxy_default
